# Jekyll configuration

name: Levi'notes
description: Welcome!

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/asyncrun

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: '/asyncrun'
## default date_format
date_format:
  title: "%B-%-d-%Y"
# Language
lan: "en"

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
